### ISSUE TITLE
Assessments settings

### ISSUE THREAD

**Issue by gjongeneel** [Azure/azure-migrate-export#21]
Hi,

When I use the latest version of the tool (v2.0.02242.55) and it creates the assessments, it will use some incorrect settings:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/18477985/220920116-1cda903e-9a00-4ffc-a51f-717b608c9bb0.png">

<img width="952" alt="image" src="https://user-images.githubusercontent.com/18477985/220921487-b2b674d1-e32f-4b1a-b935-e9b682e0de41.png">

2 - 6 all have the same error concerning VM series. A refresh or recalculate does not help.

**Comment by hvr2804** [comment]
Hello @gjongeneel , thanks for bringing this up, however, the way Azure-Migrate-Export creates assessments is using calls to Rest-Api, the Azure Portal is actually applying a filter that requires the values highlighted in red to be declared. But such is not the case, when dealing with Azure's REST API directly. When no machines are selected, it will recommend the best suitable VM based on available options.

**Comment by hvr2804** [comment]
As and when the Rest API starts failing assessment creations because of VM Series being not selected, we will start sending a list of preferred VM series, in our API calls, just as we do for SQL assessments.

**Comment by gjongeneel** [comment]
So it's normal that when the assessments are created by the Azure Migrate Export tool they show up like this in the portal, but it should not have any consequences for the results? So how can we tell which VMs are actually selected by the tool (and which are left out)?

**Comment by hvr2804** [comment]
Hello @gjongeneel this is absolutely normal. In this case we can say, that, when we select no VMs and Portal shows as 0 selected, the back end would select the most suitable VM family from all available in the drop-down. Thus, no VMs are left out.


For SQL assessments, however, we have to compulsorily provide a list of VM families, which can be seen on the Portal
