### ISSUE TITLE
Feature request - Import or use your own assessments

### ISSUE THREAD

**Issue by gjongeneel** [Azure/azure-migrate-export#22]
Hi, 

It would be a very nice feature if we would be able to use our self generated assessments. Often, we choose some other settings for generating the assessments than the default settings of this tool (for example, a comfort factor of 1.2 or we leave out some VM series). In addition, we have some other scenario's that we would like to include (for instance 1 Year options - as three years is too long for most Dutch customers - or a combination of a savings plan together with Azure Hybrid Benefit).

I guess these are the combinations included now (numbering of assessments could vary?!?):

<img width="334" alt="image" src="https://user-images.githubusercontent.com/18477985/220926144-9535b11a-cbec-4072-a756-db1566b4d1db.png">

**Comment by hvr2804** [comment]
Hello @gjongeneel , absolutely correct on your understanding of the combinations and the numbering would remain the same as you have added.

Adding @kalrashradha for, providing answer on Feature Request.
