### ISSUE TITLE
ERROR Process terminated due to exception: An item with the same key has already been added. 

### ISSUE THREAD

**Issue by JammyB** [Azure/azure-migrate-export#27]
Have run a few times and get the same error across multiple tenants.  I have run the tool before, but need to get updated data.  

One additional ask would be for a cleanup option as it does generate alot of assessments and groups within the AzMig projects.

02/03/2023-08:52:53 INFO Initiating process
02/03/2023-08:52:53 INFO Validating Tenant ID: 0f9e35dXXXXXXXXXXXXXXX
02/03/2023-08:52:53 INFO Validating Subscription: MINURSO-PROD - 01674XXXXXXXXXXXXXXXXXXXXXX
02/03/2023-08:52:53 INFO Validating Resource group: RG-AZM-MINURSO
02/03/2023-08:52:53 INFO Validating Azure Migrate project: MINUR
02/03/2023-08:52:53 INFO Validating Discovery Site name: MINUR3951mastersite
02/03/2023-08:52:53 INFO Validating Assessment Project name: MIXXXXXXXXXXXXXXXX
02/03/2023-08:52:53 INFO Validating selected source appliances: vmware,hyperv,physical
02/03/2023-08:52:53 INFO Validating Workflow: Custom
02/03/2023-08:52:53 INFO Validating Module: Discovery
02/03/2023-08:52:53 INFO Validated user input
02/03/2023-08:52:53 INFO Initiating discovered data retrieval
02/03/2023-08:52:53 INFO Deleting previous discovery reports, if any
02/03/2023-08:52:53 INFO No discovery reports found
02/03/2023-08:52:54 INFO Received discovery sites
02/03/2023-08:52:54 INFO Finished parsing discovery sites
02/03/2023-08:52:54 INFO Retrieving discovery data from VMWare sites
02/03/2023-08:52:54 INFO Retrieving discovery data from HyperV sites
02/03/2023-08:52:54 INFO Retrieving discovery data from Physical sites
02/03/2023-08:52:54 INFO Retrieved discovery data for 0 machines from HyperV sites
02/03/2023-08:52:54 INFO Retrieved discovery data for 0 machines from Physical sites
02/03/2023-08:52:55 ERROR Process terminated due to exception: An item with the same key has already been added. 
02/03/2023-08:52:55 ERROR Terminating as discovery process failed
02/03/2023-08:52:55 INFO Discovery process completed successfully

**Comment by hvr2804** [comment]
Another issue, we found out was, that:
1. Machines that were added just yesterday, don't have data for a 'Month' assessment duration setting. Probably need to add this in documentation.
2. 'Unknown' Disk type was not handled by the code. -> I will be fixing this in code

**Comment by hvr2804** [comment]
These issues are fixed with release https://github.com/Azure/azure-migrate-export/releases/tag/v2.0.02252.59.

Closing the issue.

I have informed @kalrashradha via email for feature requests:
1. Clean-up of assessments after creation of excel files on device.
2. Handling discount % on pay as you go pricing
3. (For azure migrate) Regions that do not support ultra disk for Azure Migrate APIs
